title: Project
pages: false
files:
  sortable: true

columns:
  - width: 2/3        
    sections:
      meta:
        type: fields
        fields:
          sections:
            label: Sections
            type: structure
            columns:
              col_1:
              col_2:
              bg_image:
            fields:
              num_cols:
                label: Columns
                type: toggle
                width: 1/2
                text:
                  - "1 column"
                  - "2 columns"
                show:
                  2: col_2
                hide:
                  1: col_2
              classes:
                type: text
                width: 1/2
                placeholder: Classes
              col_1:
                label: Text column (small)
                type: textarea
              col_2:
                label: Image column (large)
                type: textarea
              bg_colour:
                label: Section bg colour (HEX)
                type: text
                icon: magic
                width: 1/3
              bg_image:
                label: Section bg image
                type: files
                multiple: false
                width: 1/3
              bg_image_pos:
                label: Bg image position
                type: select
                width: 1/3
                default: full
                options:
                  left: "Left column"
                  right: "Right column"
                  full: "Full (as bg)"

  - width: 1/3
    sections:
      content:
        type: fields
        fields:
          year:
            label: Year
            type: text
            icon: calendar-o
            width: 1/3
          description:
            label: Description (1 sentence)
            type: text
            icon: font
          tags:
            label: Tags
            type: tags
            options: query
            query: 
              fetch: site.find('projects').children.pluck("tags", ",", true)
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value.slug }}"
          projecturl:
            label: Project URL
            type:  url

          h_featured:
            label: Featured
            type: headline
            width: 2/3
          featured:
            type: toggle
            width: 1/3
            options:
              0: "No"
              1: "Yes"
          featuredimage:
            label: Featured Image
            type: files
            multiple: false
            width: 1/2
          featuredcolour:
            label: Featured Color (HEX)
            type: text
            icon: magic
            width: 1/2

      files:
        label: Files
        type: files
