title: Project
pages: false
files:
  sortable: true

fields:

  h_basics:
    label: Basic
    type: headline
  title:
    label: Title
    type:  text
    width: 2/3
  year:
    label: Year
    type: text
    icon: calendar-o
    width: 1/3
  description:
    label: > 
      Description <em>(1 sentence)</em>
    type: text
    icon: font
  tags:
    label: Tags
    type:  tags
  projecturl:
    label: Project URL
    type:  url

  h_featured:
    label: Featured
    type: headline
    width: 2/3
  featured:
    label: >
      <div style="margin-top: 2rem;"></div>
    type: fieldtoggle
    width: 1/3
    options:
      0: "No"
      1: "Yes"
    show:
      1: featuredimage featuredcolour
    hide:
      0: featuredimage featuredcolour
  featuredimage:
    label: Featured Image
    type: select
    options: images
    width: 1/2
  featuredcolour:
    label: >
      Featured Color <i>(HEX)</i>
    type: text
    icon: magic
    width: 1/2

  h_content:
    label: Content
    type: headline
  sections:
    label: Sections
    type: structure
    modalsize: large
    fields:
      num_cols:
        type: fieldtoggle
        options:
          1: "One column"
          2: "Two columns"
        show:
          2: col_2
        hide:
          1: col_2
      col_1:
        label: >
          Text column <i>(small)</i>
        type: textarea
      col_2:
        label: >
          Image column <i>(large)</i>
        type: textarea
      bg_colour:
        label: >
          Section bg colour <i>(HEX)</i>
        type: text
        icon: magic
        width: 1/2
      bg_image:
        label:   >
          Section bg image <i>(Overrides colour)</i>
        type: image
        width: 1/2
    entry: >
      <table>
        <tr>
          <td width="50%" style="padding-right: 20px;">{{col_1}}</td>
          <td width="50%">{{col_2}}</td>
        </tr>
        <tr>
          <td width="50%" style="padding-top: 10px; color: #999;">bg colour: {{bg_colour}}</td>
          <td width="50%" style="padding-top: 10px; color: #999;">bg image: {{bg_image}}</td>
        <tr>
      </table>