title: Site

sections:
  listed:
    headline: Menu Pages
    type: pages
    layout: list
    status: listed
  unlisted:
    headline: Other Pages
    type: pages
    layout: list
    status: unlisted